### ISSUE TITLE
Redirect should replace instead of push

### ISSUE THREAD

**Issue by jeroenverfallie** [christianalfoni/cerebral-router#14]
For example, you ran your app 2 months with a route like `/p/928377` but now this needs to change, for reasons beyond comprehension, to `/profile/928377`

Obviously you don't want to throw away the old route, because it's heavily shared, or linked to, or just in your users their history.

In this case, you'd write something to catch this, like:

```javascript
// Redirect factory which calls Router.redirect with the new path
function redirect(replace) {
    return function(input, state, output, services) {
        const newPath = replace(input.path);

        services.router.redirect(newPath)(input, state, output, services);
    }
}

// Signal
controller.signal('redirectOldProfileRoute', redirect((path) => path.replace(/p/, 'profile')));

// Route config
export default Router(controller, {
    '/profile/:id': 'gotoProfile',
    '/p/*': 'redirectOldProfileRoute'
});
```

When you use redirect, it pushes a new history state, which makes your browser history very messy (to go back, you'd need to spam twice, etc), it should replace.

With the example above, perhaps some helper to do redirection of this kind could, would, be useful too.

**Comment by jeroenverfallie** [comment]
On top of that, named routes are perhaps something you want to avoid, but in most projects, it's unavoidable paths are going to change over the development time.

It's probably not the task of cerebral-router to provide a named route link component, but it could be a nice addon.



```
<Link name='profile-detail' params={{id: 29838}} />
```

**Comment by jeroenverfallie** [comment]
Thinking more about it, this brings the router to more configuration again, which it shouldn't do.

You could really just have this logic somewhere outside of the router anyway.

```
const routes = [
    {
        name: 'profile-detail',
        path: '/profile/:id',
        signal: 'gotoProfile'
    }
]
```

Transform and feed this into the router declaration, and use this same configuration to feed your <Link /> component.

**Comment by jeroenverfallie** [comment]
This has become a minddump, but to get back to the original issue:

There just need to be 2 methods, redirect and goto, redirect should replace and goto should push to the history.

**Comment by christianalfoni** [comment]
Hm hm,

From `addressbar` perspective it would have to expose a special method to replace url, rather than set it. All sets, `addressbar.value = "/myurl"`, will `push`, unless it is the same url. I would really like to avoid complicating and breaking the concept of `addressbar` just being an input that changes values.

I see the concern, though I would say that this is the responsibility of the server. It should redirect to the correct URL if a user has bookmarked an old url. It would just clutter the client code. Or you could "*" catch wrong url and state what url changes has been made to the app so the user can update their urls?

Lets say over 2 years with 5 url-changes the project starts to get pretty messy :-) It would be better to find strategies to make users go to the new url rather than building up legacy code?

Anyways, I am just pushing back to find other solutions as the end result of this does not make code simpler, though I can see it as more friendly from a user perspective. So yeah, lets just explore more and I am sure we will find a good solution :)

**Comment by Guria** [comment]
Redirect should definitely do `replace` by default and maybe allow `push` with optional argument

**Comment by christianalfoni** [comment]
Hm, yeah, I see the issue with looping here. But this is related to how `cerebral-router` does redirects today. I think we should take another iteration on thinking "out of the box" on this. It is not ideal that a signal redirects to an other signal at all, it being through a router or directly. I acknowledge that it seems impossible to solve it any other way, but yeah... I need to think about this some more. Will come up with alternatives :-)

**Comment by jeroenverfallie** [comment]
From a UX point of view, it definatly should be a `replace`, implementation wise we can think :)

**Comment by christianalfoni** [comment]
Added to next release, https://github.com/christianalfoni/cerebral-router/issues/44

**Comment by Guria** [comment]
christianalfoni/addressbar/issues/4
